{application,jsex,
             [{registered,[]},
              {description,"json for elixir\n"},
              {applications,[kernel,stdlib,elixir,jsx]},
              {vsn,"2.0.0"},
              {modules,['Elixir.JSEX','Elixir.JSEX.Decoder',
                        'Elixir.JSEX.Encoder','Elixir.JSEX.Encoder.Any',
                        'Elixir.JSEX.Encoder.Atom',
                        'Elixir.JSEX.Encoder.BitString',
                        'Elixir.JSEX.Encoder.Float',
                        'Elixir.JSEX.Encoder.Function',
                        'Elixir.JSEX.Encoder.HashDict',
                        'Elixir.JSEX.Encoder.Integer',
                        'Elixir.JSEX.Encoder.List','Elixir.JSEX.Encoder.Map',
                        'Elixir.JSEX.Encoder.PID','Elixir.JSEX.Encoder.Port',
                        'Elixir.JSEX.Encoder.Reference',
                        'Elixir.JSEX.Encoder.Tuple']}]}.